name: Continuous deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
      pages: write
    secrets: inherit
    uses: compulim/workflows/.github/workflows/continuous-deployment.yml@main
    with:
      github-pages: false
      node-version: 18.x
      package-name: version-from-git
